### ISSUE TITLE
RuntimeError: stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by Usama3059** [Seokju-Cho/Volumetric-Aggregation-Transformer#1]
Got this error on running on the images folder

Traceback (most recent call last):
  File "test.py", line 94, in <module>
    test_miou, test_fb_iou = test(model, dataloader_test, args.nshot)
  File "test.py", line 44, in test
    average_meter.write_result('Test', 0)
  File "/content/Volumetric-Aggregation-Transformer/common/logger.py", line 51, in write_result
    loss_buf = torch.stack(self.loss_buf)
RuntimeError: stack expects a non-empty TensorList

**Comment by Seokju-Cho** [comment]
Thank you for your interest in our research.

Can you please give us more detail? A screenshot or error message you received will help us a lot.

**Comment by Usama3059** [comment]
Actually, I have resolved this issue, further, can you tell me how to train and test on custom Dataset and also your training procedures.

**Comment by hrveda** [comment]
> 



> Actually, I have resolved this issue, further, can you tell me how to train and test on custom Dataset and also your training procedures.

@Usama3059 May I know how did you solve the issue?
