### ISSUE TITLE
Train & test code of semantic correspondence

### ISSUE THREAD

**Issue by liangsusan-git** [Seokju-Cho/Volumetric-Aggregation-Transformer#2]
Congratulations on this cool work! 
VAT achieves SOTA on multiple datasets including PF-WILLOW and Spair-71k. I am very interested in this task. However, I can not find training and test codes related to this task in the repo. I would appreciate it if you could include them in this repo.
Thank you in advance.

**Comment by SunghwanHong** [comment]
We will let you know once the update is made.

**Comment by SunghwanHong** [comment]
The updates are made!
