### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation

### ISSUE THREAD

**Issue by SirojbekSafarov** [Seokju-Cho/Volumetric-Aggregation-Transformer#6]
Hello.

Thank you for this amazing work.

I want to retrain your model, but when I traid I got this error. Do you have any experience with this error?  

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2, 128, 32, 32, 8, 8]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by Ehteshamciitwah** [comment]
I am facing the same issue. Any solution ?

**Comment by Ehteshamciitwah** [comment]
I found one solution.  we need to change the inplace operation to non -inplace operations.  There was some operation in ours.py file. i re-wrote the codes of lines. 
![image](https://user-images.githubusercontent.com/79190474/181162885-7390d3c5-00fb-460b-88c6-0505cb481135.png)
