### ISSUE TITLE
Minor Issues Downloading Some Datasets in VAT from Google Drive

### ISSUE THREAD

**Issue by Brahmagupta** [Seokju-Cho/Volumetric-Aggregation-Transformer#7]
This is just a minor issue, but I still want to bring it up.

When calling downlaod_from_google() method from ./data/download.py, the requests.Session().get(url, .......) method probably no longer returns any cookies (all I got is just an empty list) for PF-PASCAL and SPair-71k datasets, so no file is downloaded.

I checked the actual absolute url = https://docs.google.com/uc?export=download&id='file-id from download.py'. It gives a warning page saying that the file is too big that google cannot perform virus scan, and it asks you to confirm if you still want to download the file.

Seems like we still need to find another way to bypass the Google Drive Virus Scanning.

PS: there's a workaround though: just manually download the datasets into ../Datasets_CATs/. 
(Datasets_CATs/  needs to be in the parent folder of Volumetric-Aggregation-Transformer)

**Comment by SunghwanHong** [comment]
Hi, this might help you:

https://github.com/juhongm999/chm/issues/5

**Comment by Brahmagupta** [comment]
> Hi, this might help you:
> 
> [juhongm999/chm#5](https://github.com/juhongm999/chm/issues/5)

Thank you! ye changing the base url
from "https://docs.google.com/uc?"
to "https://docs.google.com/uc?export=download" did work.
