### ISSUE TITLE
rescaling the predicted keypoints coordinates

### ISSUE THREAD

**Issue by Brahmagupta** [Seokju-Cho/Volumetric-Aggregation-Transformer#9]
I'm trying to visualize some test results by using /utils_training/utils.flow2kps method. and I figured your model is trying to map keypoints from target images to src images, i.e. making predictions of keypoints in src images. (if im not mistaken). but the Estimated_kps Im getting seem off and sometimes out of range (out side of the image regions). 
I also noticed both the source and target image in a pair are resized to a same image size. this is prbly something I missed

I wonder how i can rescale the estimated_kps so it will correctly mark out the keypoints in the original images.
(Orwhat size should i rescale the original image to use the predicted keypoints)

**Comment by SunghwanHong** [comment]
Hi, sorry for the late reply.
If you see this code : 
    flow = F.interpolate(flow, upsample_size, mode='bilinear') * (upsample_size[0] / h)
We only recale it using "h". This means that we assumed h==w. So if you want to obtain keypoints that are h!=w, then you could do something like this
    flow[0] = F.interpolate(flow[0], upsample_size[0], mode='bilinear') * (upsample_size[0] / h)
flow[1] = F.interpolate(flow[1], upsample_size[1], mode='bilinear') * (upsample_size[1] / w)
